### ISSUE TITLE
Error in FStitch step 

### ISSUE THREAD

**Issue by daramirez** [Dowell-Lab/Nascent-Flow#8]
Hi,

When using nascent-flow, I get an error in the FStitch step. 
I think it goes back to the following error:
PermissionError: [Errno 13] Permission denied: '/opt/rseqc/python-2.7.14/2.6.4/lib/python2.7/site-packages/RSeQC-2.6.4-py2.7.egg-info/PKG-INFO'

Here attached are three files:
The pipeline report after the crash
[pipeline_report.txt](https://github.com/Dowell-Lab/Nascent-Flow/files/3418455/pipeline_report.txt)

The sbatch script I used
[nascentflow.txt](https://github.com/Dowell-Lab/Nascent-Flow/files/3418457/nascentflow.txt)

And the config file, which just for the purpose of attaching it here, I added the suffix .txt
[slurm_grch38.config.txt](https://github.com/Dowell-Lab/Nascent-Flow/files/3418460/slurm_grch38.config.txt)

I hope that you can help me solve this issue.
Thanks!

**Comment by daramirez** [comment]
I also want to add that I have gone and looked at the files in the temporary directory where FStitch is working

/scratch/Users/dara6367/data/PRO-seq_A549-IFNB/201907/replicate-2/temp/a0/c84f6969676c6395e083f24b5a63fe

I cannot find anything additional than what the pipeline_report.txt already tells me, including when I check the .command.err, .command.log or .command.run files.

**Comment by magruca** [comment]
@daramirez Hey sorry for the delayed response! For whatever reason I didn't get a notification for this. Feel free to swing by if this happens again. So there's a conflict between python 2 & python 3. If you get rid of the module load python/2.7.14/rseqc/2.6.4 and replace it with the python 3 version module load python/3.6.3/rseqc/3.0.0 it should be resolved. Let me know if you still have any issues after this.

**Comment by daramirez** [comment]
It worked.
Thank you, Margaret.
